name: JoinBroadcast
main: ImagicalCorp\Main
version: 1.0.0
api: [1.0.0]
author: Imagical Corporation
description: Broadcast join messages when a player joins.
website: http://imagicalcorp.github.io/JoinBroadcast
